feat(SignIn): store token additonally
kishorepmr/components pull request #5
Opened 2022-02-08 13:06 UTC by kishorepmr

[SPARK-301564](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-301564)

## Description:

- Store access tokens to cookies, local or session storage additionally if needed

2022-02-08 13:22 UTC, varunnai approved these changes

2022-02-08 13:22 UTC, varunnai commented on src/components/SignIn/SignIn.jsx
> +              case 'cookie':
if you see that there's a need for these strings to be used in multiple places now or in the future please move to some sort of constants and use it from there

2022-02-10 06:52 UTC, mokandre approved these changes

2022-02-14 07:45 UTC, mokandre requested changes

2022-02-14 07:45 UTC, mokandre commented on src/components/SignIn/SignIn.stories.js
> +    if (res.data.access_token) {
can we check and access `access_token` like res?.data?.access_token

2022-02-14 09:42 UTC, mokandre approved these changes

2022-02-14 09:42 UTC, merged